version: '3.8'

services:
  gerador:
    build: ./gerador
    volumes:
      - ./gerador:/app
    command: python gerador.py
    restart: unless-stopped

  tratamento:
    build: ./tratamento
    volumes:
      - ./tratamento:/app
    command: Rscript tratamento.R
    depends_on:
      - gerador
    restart: unless-stopped

  analise:
    build: ./analise
    volumes:
      - ./analise:/app
    # Adicione um script de execução se houver (ex: grafico.py)
    restart: unless-stopped

  web:
    build: ./web
    volumes:
      - ./web:/app
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - analise
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
